<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>$(MSBuildProjectName.Replace(" MiApiCuadrado", "MiWebApi"))</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);MiWebApi.Tests\**;BlazorClient\**;WinFormsClient\**;</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.6" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BlazorClient\**" />
    <Content Remove="BlazorClient\**" />
    <EmbeddedResource Remove="BlazorClient\**" />
    <None Remove="BlazorClient\**" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="WinFormsClient\**" />
		<Content Remove="WinFormsClient\**" />
		<EmbeddedResource Remove="WinFormsClient\**" />
		<None Remove="WinFormsClient\**" />
	</ItemGroup>

</Project>
